attributes_dict = {
    "package": "package",
    "class_name": "class",
    "text": "text",
    "resource_id": "resource-id",
    "content_desc": "content-desc",
    "checkable": "checkable",
    "checked": "checked",
    "clickable": "clickable",
    "enabled": "enabled",
    "focusable": "focusable",
    "focused": "focused",
    "long_clickable": "long-clickable",
    "password": "password",
    "scrollable": "scrollable",
    "selected": "selected",
    "bounds": "bounds",
}
